---
- name: docker install & start services
  hosts: RHEL
  become: yes

  tasks:
  - name: 1. Install required packages
    yum:
      name: '{{ item }}'
      state: latest
    loop:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2

  - name: 2. Add Docker repo
    get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

  - name: 3. Install Docker
    yum:
      name: docker-ce
      state: latest

  - name: 4. Start Docker service
    service:
      name: docker
      state: started
      enabled: yes

  - name: 5. Verify Docker be installed
    command: docker run --rm hello-world
